### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "cookie-test12@test.com",
  "password": "jupiter"
}

### Sign in a user
### If the cookie is already set on the session (calling this after signup), 
### it might seem like cookie is not sent, but it's actually not changed, 
### so it gets ignored
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "cookie-test1@test.com",
  "password": "jupiter"
}

### Sign out currently singed in user
POST  http://localhost:3000/auth/signout

### Get currently singed in user
GET http://localhost:3000/auth/whoami

### Find a particular user with a given ID 
GET http://localhost:3000/auth/3


### Find all users with a given email
GET http://localhost:3000/auth?email=abc@test.com


### Delete a user with a given id 
DELETE http://localhost:3000/auth/7


### Update a user
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
  "password": "PASS"
}

# ### Set a color 
# GET http://localhost:3000/auth/colors/redBlue

# ### Get the color
# GET http://localhost:3000/auth/colors